
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE0_NANO_SOC_practica(

	//////////// ADC //////////
	output		          		ADC_CONVST,
	output		          		ADC_SCK,
	output		          		ADC_SDI,
	input 		          		ADC_SDO,

	//////////// ARDUINO //////////
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,

	//////////// CLOCK //////////
	input 		          		FPGA_CLK1_50,
	input 		          		FPGA_CLK2_50,
	input 		          		FPGA_CLK3_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// GPIO_0, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_0,

	//////////// GPIO_1, GPIO connect to GPIO Default //////////
	inout 		    [35:0]		GPIO_1
);



//=======================================================
//  REG/WIRE declarations
//=======================================================





wire div_freq_clk;
assign LED[0]=div_freq_clk;
//=======================================================
//  Structural coding
//=======================================================

divisor_frecuencia divisor_frecuencia_inst
(
	.clk(FPGA_CLK1_50) ,	// input  clk_sig
	.reset(1'b1) ,	// input  reset_sig
	.in(32'd25000000) ,	// input [31:0] in_sig
	.divf(div_freq_clk) 	// output  divf_sig
);


contador contador_inst
(
	.clk(div_freq_clk) ,	// input  clk_sig
	.reset(1'b1) ,	// input  reset_sig
	.out(LED[7:1]) 	// output [9:0] out_sig
);



endmodule
