
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module Santoto_ejemplo1(

	//////////// CLOCK //////////
	input 		          		CLOCK_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// GPIO_0, GPIO_0 connect to GPIO Default //////////
	inout 		    [35:0]		GPIO
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

wire clk_5Mhz;
wire clk_1hz;
//=======================================================
//  Structural coding
//=======================================================


divisor_frecuencia divisor_frecuencia_inst
(
	.clk(CLOCK_50) ,	// input  clk_sig
	.reset(KEY[0]) ,	// input  reset_sig
	.in(32'd25000000) ,	// input [31:0] in_sig
	.divf(clk_1hz) 	// output  divf_sig
);

pll_contador reloj_contador(
		.refclk(CLOCK_50),   //  refclk.clk
		.rst(SW[0]),      //   reset.reset
		.outclk_0(clk_5Mhz), // outclk0.clk
		.locked()    //  locked.export
	);

contador contador1
(
	.clk(clk_1hz) ,	// input  clk_sig
	.reset(KEY[0]) ,	// input  reset_sig
	.out(LEDR[9:0]) 	// output [9:0] out_sig
);



endmodule
